package ObjectRepository;

public class ReportViewerPageOR {

	public String reportsEditorWindow_Xpath;
	public String reportsTitleBar_Xpath;
	public String signReportButton_Xpath;
	public String signReportDialog_Xpath;
	public String signReportYesButton_Name;
	public String saveReportDialog_Xpath;
	public String saveReportDialogSaveButton_Name;
	public String saveReportDialogDontSaveButton_Name;
	public String closeReportButton_Name;
	public String sendFaxEmailDialog_Xpath;
	public String reportViewerWindow_Xpath;
	public String printWindow_Xpath;
	public String printWindowCancelButton_Xpath;
	public String saveReportTemplateWindow_Name;
	public String saveReportTemplateNameTextbox_Name;
	public String reportValidationPopup_Name;
	public String dialogButton_Xpath;
	public String changePhrasePopup_Name;
	public String baselineLabel_Xpath;
	public String reportValidationErrorDialogBox_Xpath;
	public String reportValidationErrorOkButton_Name;
	public String reportDynamicPreview_Xpath;
	public String reportEditorTab_Xpath;
	public String reportDynamicPreviewWindow_Name;
	public String reportEditorMaximizeButton_Xpath;
	public String reportEditorRestoreButton_Xpath;
	public String saveReport_Name;
	public String savingReportProgressWindow_Xpath;
	public String setComparisonBaselineContextMenuItem_Name;
	public String meanCalculationDialog_Xpath;
	public String meanCalculationDataGrid_Xpath;
	public String meanCalculationDataItem_Xpath;
	public String deselectAllButton_Name;
	public String saveResourcesDialog_Xpath;
	public String fitWidth_Name;
	public String zoomIn_Name;
	public String zoomOut_Name;
	public String fitPage_Name;
	public String saveTemplate_Name;
	public String actualSize_Name;
	public String comparisonBaseline_Name;
	public String nextPage_Name;
	public String comparisonBaselineReportName_Xpath;
	public String menuBarOption_Xpath;
	public String menuOption_Xpath;
	public String menuItem_Xpath;
	public String reportViewerSubMenuOption_Xpath;
	public String reportViewerMenuOption_Xpath;
}
